/**
 * Philippine cities (chartered + component) for the launch region. Used to populate a datalist for
 * the city field; the input still accepts free text, so an unlisted municipality can be typed.
 * (Sourced from the v1 reference asset; see notes.md "Relationship to the v1 app".)
 */
export const PH_CITIES: readonly string[] = [
  'Alaminos',
  'Angeles',
  'Antipolo',
  'Bacolod',
  'Bacoor',
  'Bago',
  'Baguio',
  'Bais',
  'Balanga',
  'Baliwag',
  'Batac',
  'Batangas City',
  'Bayawan',
  'Baybay',
  'Bayugan',
  'Biñan',
  'Bislig',
  'Bogo',
  'Borongan',
  'Butuan',
  'Cabadbaran',
  'Cabanatuan',
  'Cabuyao',
  'Cadiz',
  'Cagayan de Oro',
  'Calaca',
  'Calamba',
  'Calapan',
  'Calbayog',
  'Caloocan',
  'Candon',
  'Canlaon',
  'Carcar',
  'Carmona',
  'Catbalogan',
  'Cauayan',
  'Cavite City',
  'Cebu City',
  'Cotabato City',
  'Dagupan',
  'Danao',
  'Dapitan',
  'Dasmariñas',
  'Davao City',
  'Digos',
  'Dipolog',
  'Dumaguete',
  'El Salvador',
  'Escalante',
  'Gapan',
  'General Santos',
  'General Trias',
  'Gingoog',
  'Guihulngan',
  'Himamaylan',
  'Ilagan',
  'Iligan',
  'Iloilo City',
  'Imus',
  'Iriga',
  'Isabela (Basilan)',
  'Kabankalan',
  'Kidapawan',
  'Koronadal',
  'La Carlota',
  'Labo',
  'Lamitan',
  'Laoag',
  'Lapu-Lapu',
  'Las Piñas',
  'Legazpi',
  'Ligao',
  'Lipa',
  'Lucena',
  'Maasin',
  'Mabalacat',
  'Makati',
  'Malabon',
  'Malaybalay',
  'Malolos',
  'Mandaluyong',
  'Mandaue',
  'Manila',
  'Marawi',
  'Marikina',
  'Masbate City',
  'Mati',
  'Meycauayan',
  'Muñoz',
  'Muntinlupa',
  'Naga (Camarines Sur)',
  'Naga (Cebu)',
  'Navotas',
  'Olongapo',
  'Ormoc',
  'Oroquieta',
  'Ozamiz',
  'Pagadian',
  'Palayan',
  'Panabo',
  'Parañaque',
  'Pasay',
  'Pasig',
  'Passi',
  'Puerto Princesa',
  'Quezon City',
  'Roxas',
  'Sagay',
  'Samal',
  'San Carlos (Negros Occidental)',
  'San Carlos (Pangasinan)',
  'San Fernando (La Union)',
  'San Fernando (Pampanga)',
  'San Jose (Nueva Ecija)',
  'San Jose del Monte',
  'San Juan',
  'San Pablo',
  'San Pedro',
  'Santa Rosa',
  'Santiago',
  'Silay',
  'Sipalay',
  'Sorsogon City',
  'Surigao City',
  'Tabaco',
  'Tabuk',
  'Tacloban',
  'Tacurong',
  'Tagaytay',
  'Tagbilaran',
  'Taguig',
  'Tagum',
  'Talisay (Cebu)',
  'Talisay (Negros Occidental)',
  'Tanauan',
  'Tandag',
  'Tangub',
  'Tanjay',
  'Tarlac City',
  'Tayabas',
  'Toledo',
  'Trece Martires',
  'Tuguegarao',
  'Urdaneta',
  'Valencia',
  'Valenzuela',
  'Victorias',
  'Vigan',
  'Zamboanga City',
];
