/**
 * Canonical Philippine city/municipality names (master_plan §2AI - strict City validation).
 *
 * `PH_CITIES` is the de-duplicated, alphabetically sorted, Title-Cased list of EVERY Philippine
 * city and municipality, derived from the PSGC city/municipality dataset (1648 places,
 * source: github.com/jgngo/psgc-data, based on the PSA PSGC publication). It is a genuine flat name
 * list - it feeds both the onboarding/edit `CityCombobox` picker and the `isValidPhCity` validator,
 * so registration rejects garbage (e.g. "Za" or a bare province like "Bulacan") but never blocks a
 * real resident. Cities carry their real "<Name> City" display form (e.g. `Zamboanga City`,
 * `Davao City`, `Toledo City`); municipalities keep their plain name (e.g. `Jolo`, `Titay`,
 * `Santo Tomas`). Places sharing a name across provinces (there are ~200 - many "Santa Cruz",
 * "San Isidro", etc.) collapse to a single entry, so the list (~1423) is shorter than the
 * raw place count; a resident of any of them still validates. The two independent "garden/science
 * city" long forms are stored by their common short names (`Samal`, `Muñoz`), and the Bulacan-province
 * town uses PSA's current spelling `Bulakan` so the bare province name "Bulacan" stays invalid.
 *
 * `normalizeCity` is pure and idempotent: it resolves case/whitespace/"City"-suffix/"City of"-prefix
 * variants and a small map of real live-data typos onto the canonical entry, and otherwise returns a
 * cleaned Title-Case version of the input unchanged (it never blanks or drops data). `isValidPhCity`
 * normalizes then tests exact membership in `PH_CITIES`.
 */

/** Canonical Philippine city/municipality display names, de-duplicated and alphabetically sorted. */
export const PH_CITIES: readonly string[] = [
  'Aborlan',
  'Abra de Ilog',
  'Abucay',
  'Abulug',
  'Abuyog',
  'Adams',
  'Agdangan',
  'Aglipay',
  'Agno',
  'Agoncillo',
  'Agoo',
  'Aguilar',
  'Aguinaldo',
  'Agutaya',
  'Ajuy',
  'Akbar',
  'Al-Barka',
  'Alabat',
  'Alabel',
  'Alamada',
  'Alaminos',
  'Alaminos City',
  'Alangalang',
  'Albuera',
  'Alburquerque',
  'Alcala',
  'Alcantara',
  'Alcoy',
  'Alegria',
  'Aleosan',
  'Alfonso',
  'Alfonso Castaneda',
  'Alfonso Lista',
  'Aliaga',
  'Alicia',
  'Alilem',
  'Alimodian',
  'Alitagtag',
  'Allacapan',
  'Allen',
  'Almagro',
  'Almeria',
  'Aloguinsan',
  'Aloran',
  'Altavas',
  'Alubijid',
  'Amadeo',
  'Ambaguio',
  'Amlan',
  'Ampatuan',
  'Amulung',
  'Anahawan',
  'Anao',
  'Anda',
  'Angadanan',
  'Angat',
  'Angeles City',
  'Angono',
  'Anilao',
  'Anini-Y',
  'Antequera',
  'Antipas',
  'Antipolo City',
  'Apalit',
  'Aparri',
  'Araceli',
  'Arakan',
  'Arayat',
  'Argao',
  'Aringay',
  'Aritao',
  'Aroroy',
  'Arteche',
  'Asingan',
  'Asipulo',
  'Asturias',
  'Asuncion',
  'Atimonan',
  'Atok',
  'Aurora',
  'Ayungon',
  'Baao',
  'Babatngon',
  'Bacacay',
  'Bacarra',
  'Baclayon',
  'Bacnotan',
  'Baco',
  'Bacolod',
  'Bacolod City',
  'Bacolod-Kalawi',
  'Bacolor',
  'Bacong',
  'Bacoor City',
  'Bacuag',
  'Bacungan',
  'Badian',
  'Badiangan',
  'Badoc',
  'Bagabag',
  'Bagac',
  'Bagamanoc',
  'Baganga',
  'Baggao',
  'Bago City',
  'Baguio City',
  'Bagulin',
  'Bagumbayan',
  'Bais City',
  'Bakun',
  'Balabac',
  'Balabagan',
  'Balagtas',
  'Balamban',
  'Balanga City',
  'Balangiga',
  'Balangkayan',
  'Balaoan',
  'Balasan',
  'Balatan',
  'Balayan',
  'Balbalan',
  'Baleno',
  'Baler',
  'Balete',
  'Baliangao',
  'Baliguian',
  'Balilihan',
  'Balindong',
  'Balingasag',
  'Balingoan',
  'Baliuag',
  'Ballesteros',
  'Baloi',
  'Balud',
  'Balungao',
  'Bamban',
  'Bambang',
  'Banate',
  'Banaue',
  'Banaybanay',
  'Banayoyo',
  'Banga',
  'Bangar',
  'Bangued',
  'Bangui',
  'Bani',
  'Banisilan',
  'Banna',
  'Bansalan',
  'Bansud',
  'Bantay',
  'Bantayan',
  'Banton',
  'Baras',
  'Barbaza',
  'Barcelona',
  'Barili',
  'Barira',
  'Barlig',
  'Barobo',
  'Barotac Nuevo',
  'Barotac Viejo',
  'Baroy',
  'Barugo',
  'Basay',
  'Basco',
  'Basey',
  'Basilisa',
  'Basista',
  'Basud',
  'Batac City',
  'Batad',
  'Batan',
  'Batangas City',
  'Bataraza',
  'Bato',
  'Batuan',
  'Bauan',
  'Bauang',
  'Bauko',
  'Baungon',
  'Bautista',
  'Bay',
  'Bayabas',
  'Bayambang',
  'Bayang',
  'Bayawan City',
  'Baybay City',
  'Bayog',
  'Bayombong',
  'Bayugan City',
  'Belison',
  'Benito Soliven',
  'Besao',
  'Bien Unido',
  'Bilar',
  'Biliran',
  'Binalbagan',
  'Binalonan',
  'Biñan City',
  'Binangonan',
  'Bindoy',
  'Bingawan',
  'Binidayan',
  'Binmaley',
  'Binondo',
  'Binuangan',
  'Biri',
  'Bislig City',
  'Boac',
  'Bobon',
  'Bocaue',
  'Bogo City',
  'Bokod',
  'Bolinao',
  'Boliney',
  'Boljoon',
  'Bombon',
  'Bongabon',
  'Bongabong',
  'Bongao',
  'Bonifacio',
  'Bontoc',
  'Borbon',
  'Borongan City',
  'Boston',
  'Botolan',
  'Braulio E. Dujali',
  "Brooke'S Point",
  'Buadiposo-Buntong',
  'Bubong',
  'Bucay',
  'Bucloc',
  'Buenavista',
  'Bugallon',
  'Bugasong',
  'Buguey',
  'Buguias',
  'Buhi',
  'Bula',
  'Bulakan',
  'Bulalacao',
  'Bulan',
  'Buldon',
  'Buluan',
  'Bulusan',
  'Bumbaran',
  'Bunawan',
  'Burauen',
  'Burdeos',
  'Burgos',
  'Buruanga',
  'Bustos',
  'Busuanga',
  'Butig',
  'Butuan City',
  'Buug',
  'Caba',
  'Cabadbaran City',
  'Cabagan',
  'Cabanatuan City',
  'Cabangan',
  'Cabanglasan',
  'Cabarroguis',
  'Cabatuan',
  'Cabiao',
  'Cabucgayan',
  'Cabugao',
  'Cabusao',
  'Cabuyao City',
  'Cadiz City',
  'Cagayan de Oro City',
  'Cagayancillo',
  'Cagdianao',
  'Cagwait',
  'Caibiran',
  'Cainta',
  'Cajidiocan',
  'Calabanga',
  'Calaca',
  'Calamba',
  'Calamba City',
  'Calanasan',
  'Calanogas',
  'Calapan City',
  'Calape',
  'Calasiao',
  'Calatagan',
  'Calatrava',
  'Calauag',
  'Calauan',
  'Calayan',
  'Calbayog City',
  'Calbiga',
  'Calinog',
  'Calintaan',
  'Caloocan City',
  'Calubian',
  'Calumpit',
  'Caluya',
  'Camalaniugan',
  'Camalig',
  'Camaligan',
  'Camiling',
  'Can-Avid',
  'Canaman',
  'Candaba',
  'Candelaria',
  'Candijay',
  'Candon City',
  'Candoni',
  'Canlaon City',
  'Cantilan',
  'Caoayan',
  'Capalonga',
  'Capas',
  'Capoocan',
  'Capul',
  'Caraga',
  'Caramoan',
  'Caramoran',
  'Carasi',
  'Carcar City',
  'Cardona',
  'Carigara',
  'Carles',
  'Carmen',
  'Carmona',
  'Carranglan',
  'Carrascal',
  'Casiguran',
  'Castilla',
  'Castillejos',
  'Cataingan',
  'Catanauan',
  'Catarman',
  'Catbalogan City',
  'Cateel',
  'Catigbian',
  'Catmon',
  'Catubig',
  'Cauayan',
  'Cauayan City',
  'Cavinti',
  'Cavite City',
  'Cawayan',
  'Cebu City',
  'Cervantes',
  'Clarin',
  'Claver',
  'Claveria',
  'Columbio',
  'Compostela',
  'Concepcion',
  'Conner',
  'Consolacion',
  'Corcuera',
  'Cordon',
  'Cordova',
  'Corella',
  'Coron',
  'Cortes',
  'Cotabato City',
  'Cuartero',
  'Cuenca',
  'Culaba',
  'Culasi',
  'Culion',
  'Currimao',
  'Cuyapo',
  'Cuyo',
  'Daanbantayan',
  'Daet',
  'Dagami',
  'Dagohoy',
  'Daguioman',
  'Dagupan City',
  'Dalaguete',
  'Damulog',
  'Danao',
  'Danao City',
  'Dangcagan',
  'Danglas',
  'Dao',
  'Dapa',
  'Dapitan City',
  'Daraga',
  'Daram',
  'Dasmariñas City',
  'Dasol',
  'Datu Abdullah Sangki',
  'Datu Anggal Midtimbang',
  'Datu Blah T. Sinsuat',
  'Datu Hoffer Ampatuan',
  'Datu Odin Sinsuat',
  'Datu Paglas',
  'Datu Piang',
  'Datu Salibo',
  'Datu Saudi-Ampatuan',
  'Datu Unsay',
  'Dauin',
  'Dauis',
  'Davao City',
  'Del Carmen',
  'Del Gallego',
  'Delfin Albano',
  'Diadi',
  'Diffun',
  'Digos City',
  'Dilasag',
  'Dimasalang',
  'Dimataling',
  'Dimiao',
  'Dinagat',
  'Dinalungan',
  'Dinalupihan',
  'Dinapigue',
  'Dinas',
  'Dingalan',
  'Dingle',
  'Dingras',
  'Dipaculao',
  'Diplahan',
  'Dipolog City',
  'Ditsaan-Ramain',
  'Divilacan',
  'Dolores',
  'Don Carlos',
  'Don Marcelino',
  'Don Victoriano Chiongbian',
  'Doña Remedios Trinidad',
  'Donsol',
  'Dueñas',
  'Duero',
  'Dulag',
  'Dumaguete City',
  'Dumalag',
  'Dumalinao',
  'Dumalneg',
  'Dumangas',
  'Dumanjug',
  'Dumaran',
  'Dumarao',
  'Dumingag',
  'Dupax del Norte',
  'Dupax del Sur',
  'Echague',
  'El Nido',
  'El Salvador City',
  'Enrile',
  'Enrique B. Magalona',
  'Enrique Villanueva',
  'Ermita',
  'Escalante City',
  'Esperanza',
  'Estancia',
  'Famy',
  'Ferrol',
  'Flora',
  'Floridablanca',
  'Gabaldon',
  'Gainza',
  'Galimuyod',
  'Gamay',
  'Gamu',
  'Ganassi',
  'Gandara',
  'Gapan City',
  'Garchitorena',
  'Garcia Hernandez',
  'Gasan',
  'Gattaran',
  'Gen. Mariano Alvarez',
  'Gen. S.K. Pendatun',
  'General Emilio Aguinaldo',
  'General Luna',
  'General Macarthur',
  'General Mamerto Natividad',
  'General Nakar',
  'General Santos City',
  'General Tinio',
  'General Trias City',
  'Gerona',
  'Getafe',
  'Gigaquit',
  'Gigmoto',
  'Ginatilan',
  'Gingoog City',
  'Giporlos',
  'Gitagum',
  'Glan',
  'Gloria',
  'Goa',
  'Godod',
  'Gonzaga',
  'Governor Generoso',
  'Gregorio del Pilar',
  'Guagua',
  'Gubat',
  'Guiguinto',
  'Guihulngan City',
  'Guimba',
  'Guimbal',
  'Guinayangan',
  'Guindulman',
  'Guindulungan',
  'Guinobatan',
  'Guinsiliban',
  'Guipos',
  'Guiuan',
  'Gumaca',
  'Gutalac',
  'Hadji Mohammad Ajul',
  'Hadji Muhtamad',
  'Hadji Panglima Tahil',
  'Hagonoy',
  'Hamtic',
  'Hermosa',
  'Hernani',
  'Hilongos',
  'Himamaylan City',
  'Hinabangan',
  'Hinatuan',
  'Hindang',
  'Hingyon',
  'Hinigaran',
  'Hinoba-An',
  'Hinunangan',
  'Hinundayan',
  'Hungduan',
  'Iba',
  'Ibaan',
  'Ibajay',
  'Igbaras',
  'Iguig',
  'Ilagan City',
  'Iligan City',
  'Ilog',
  'Iloilo City',
  'Imelda',
  'Impasug-Ong',
  'Imus City',
  'Inabanga',
  'Indanan',
  'Indang',
  'Infanta',
  'Initao',
  'Inopacan',
  'Intramuros',
  'Ipil',
  'Iriga City',
  'Irosin',
  'Isabel',
  'Isabela',
  'Isabela City',
  'Isulan',
  'Itbayat',
  'Itogon',
  'Ivana',
  'Ivisan',
  'Jabonga',
  'Jaen',
  'Jagna',
  'Jala-Jala',
  'Jamindan',
  'Janiuay',
  'Jaro',
  'Jasaan',
  'Javier',
  'Jiabong',
  'Jimalalud',
  'Jimenez',
  'Jipapad',
  'Jolo',
  'Jomalig',
  'Jones',
  'Jordan',
  'Jose Abad Santos',
  'Jose Dalman',
  'Jose Panganiban',
  'Josefina',
  'Jovellar',
  'Juban',
  'Julita',
  'Kabacan',
  'Kabankalan City',
  'Kabasalan',
  'Kabayan',
  'Kabugao',
  'Kabuntalan',
  'Kadingilan',
  'Kalamansig',
  'Kalawit',
  'Kalayaan',
  'Kalibo',
  'Kalilangan',
  'Kalingalan Caluang',
  'Kananga',
  'Kapai',
  'Kapalong',
  'Kapangan',
  'Kapatagan',
  'Kasibu',
  'Katipunan',
  'Kauswagan',
  'Kawayan',
  'Kawit',
  'Kayapa',
  'Kiamba',
  'Kiangan',
  'Kibawe',
  'Kiblawan',
  'Kibungan',
  'Kidapawan City',
  'Kinoguitan',
  'Kitaotao',
  'Kitcharao',
  'Kolambugan',
  'Koronadal City',
  'Kumalarang',
  'La Carlota City',
  'La Castellana',
  'La Libertad',
  'La Paz',
  'La Trinidad',
  'Laak',
  'Labangan',
  'Labason',
  'Labo',
  'Labrador',
  'Lacub',
  'Lagangilang',
  'Lagawe',
  'Lagayan',
  'Lagonglong',
  'Lagonoy',
  'Laguindingan',
  'Lake Sebu',
  'Lakewood',
  'Lal-Lo',
  'Lala',
  'Lambayong',
  'Lambunao',
  'Lamitan City',
  'Lamut',
  'Langiden',
  'Languyan',
  'Lantapan',
  'Lantawan',
  'Lanuza',
  'Laoac',
  'Laoag City',
  'Laoang',
  'Lapinig',
  'Lapu-Lapu City',
  'Lapuyan',
  'Larena',
  'Las Navas',
  'Las Nieves',
  'Las Piñas City',
  'Lasam',
  'Laua-An',
  'Laur',
  'Laurel',
  'Lavezares',
  'Lawaan',
  'Lazi',
  'Lebak',
  'Leganes',
  'Legazpi City',
  'Lemery',
  'Leon',
  'Leyte',
  'Lezo',
  'Lian',
  'Lianga',
  'Libacao',
  'Libagon',
  'Libertad',
  'Libjo',
  'Libmanan',
  'Libon',
  'Libona',
  'Libungan',
  'Licab',
  'Licuan-Baay',
  'Lidlidda',
  'Ligao City',
  'Lila',
  'Liliw',
  'Liloan',
  'Liloy',
  'Limasawa',
  'Limay',
  'Linamon',
  'Linapacan',
  'Lingayen',
  'Lingig',
  'Lipa City',
  'Llanera',
  'Llorente',
  'Loay',
  'Lobo',
  'Loboc',
  'Looc',
  'Loon',
  'Lope de Vega',
  'Lopez',
  'Lopez Jaena',
  'Loreto',
  'Los Baños',
  'Luba',
  'Lubang',
  'Lubao',
  'Lubuagan',
  'Lucban',
  'Lucena City',
  'Lugait',
  'Lugus',
  'Luisiana',
  'Lumba-Bayabao',
  'Lumbaca-Unayan',
  'Lumban',
  'Lumbatan',
  'Lumbayanague',
  'Luna',
  'Lupao',
  'Lupi',
  'Lupon',
  'Lutayan',
  'Luuk',
  "M'Lang",
  'Ma-Ayon',
  'Maasim',
  'Maasin',
  'Maasin City',
  'Mabalacat City',
  'Mabinay',
  'Mabini',
  'Mabitac',
  'Mabuhay',
  'Macabebe',
  'Macalelon',
  'Macarthur',
  'Maco',
  'Maconacon',
  'Macrohon',
  'Madalag',
  'Madalum',
  'Madamba',
  'Maddela',
  'Madrid',
  'Madridejos',
  'Magalang',
  'Magallanes',
  'Magarao',
  'Magdalena',
  'Magdiwang',
  'Magpet',
  'Magsaysay',
  'Magsingal',
  'Maguing',
  'Mahaplag',
  'Mahatao',
  'Mahayag',
  'Mahinog',
  'Maigo',
  'Maimbung',
  'Mainit',
  'Maitum',
  'Majayjay',
  'Makati City',
  'Makato',
  'Makilala',
  'Malabang',
  'Malabon City',
  'Malabuyoc',
  'Malalag',
  'Malangas',
  'Malapatan',
  'Malasiqui',
  'Malate',
  'Malay',
  'Malaybalay City',
  'Malibcong',
  'Malilipot',
  'Malimono',
  'Malinao',
  'Malita',
  'Malitbog',
  'Mallig',
  'Malolos City',
  'Malungon',
  'Maluso',
  'Malvar',
  'Mamasapano',
  'Mambajao',
  'Mamburao',
  'Mambusao',
  'Manabo',
  'Manaoag',
  'Manapla',
  'Manay',
  'Mandaluyong City',
  'Mandaon',
  'Mandaue City',
  'Mangaldan',
  'Mangatarem',
  'Mangudadatu',
  'Manila City',
  'Manito',
  'Manjuyod',
  'Mankayan',
  'Manolo Fortich',
  'Mansalay',
  'Manticao',
  'Manukan',
  'Mapanas',
  'Mapandan',
  'Mapun',
  'Marabut',
  'Maragondon',
  'Maragusan',
  'Maramag',
  'Marantao',
  'Marawi City',
  'Marcos',
  'Margosatubig',
  'Maria',
  'Maria Aurora',
  'Maribojoc',
  'Marihatag',
  'Marikina City',
  'Marilao',
  'Maripipi',
  'Mariveles',
  'Marogong',
  'Masantol',
  'Masbate City',
  'Masinloc',
  'Masiu',
  'Maslog',
  'Mataasnakahoy',
  'Matag-Ob',
  'Matalam',
  'Matalom',
  'Matanao',
  'Matanog',
  'Mati City',
  'Matnog',
  'Matuguinao',
  'Matungao',
  'Mauban',
  'Mawab',
  'Mayantoc',
  'Maydolong',
  'Mayorga',
  'Mayoyao',
  'Medellin',
  'Medina',
  'Mendez',
  'Mercedes',
  'Merida',
  'Mexico',
  'Meycauayan City',
  'Miagao',
  'Midsalip',
  'Midsayap',
  'Milagros',
  'Milaor',
  'Mina',
  'Minalabac',
  'Minalin',
  'Minglanilla',
  'Moalboal',
  'Mobo',
  'Mogpog',
  'Moises Padilla',
  'Molave',
  'Moncada',
  'Mondragon',
  'Monkayo',
  'Monreal',
  'Montevista',
  'Morong',
  'Motiong',
  'Mulanay',
  'Mulondo',
  'Munai',
  'Muñoz',
  'Muntinlupa City',
  'Murcia',
  'Mutia',
  'Naawan',
  'Nabas',
  'Nabua',
  'Nabunturan',
  'Naga',
  'Naga City',
  'Nagbukel',
  'Nagcarlan',
  'Nagtipunan',
  'Naguilian',
  'Naic',
  'Nampicuan',
  'Narra',
  'Narvacan',
  'Nasipit',
  'Nasugbu',
  'Natividad',
  'Natonin',
  'Naujan',
  'Naval',
  'Navotas City',
  'New Bataan',
  'New Corella',
  'New Lucena',
  'New Washington',
  'Norala',
  'Northern Kabuntalan',
  'Norzagaray',
  'Noveleta',
  'Nueva Era',
  'Nueva Valencia',
  'Numancia',
  'Nunungan',
  'Oas',
  'Obando',
  'Ocampo',
  'Odiongan',
  'Old Panamao',
  'Olongapo City',
  'Olutanga',
  'Omar',
  'Opol',
  'Orani',
  'Oras',
  'Orion',
  'Ormoc City',
  'Oroquieta City',
  'Oslob',
  'Oton',
  'Ozamiz City',
  'Paco',
  'Padada',
  'Padre Burgos',
  'Padre Garcia',
  'Paete',
  'Pagadian City',
  'Pagagawan',
  'Pagalungan',
  'Pagayawan',
  'Pagbilao',
  'Paglat',
  'Pagsanghan',
  'Pagsanjan',
  'Pagudpud',
  'Pakil',
  'Palanan',
  'Palanas',
  'Palapag',
  'Palauig',
  'Palayan City',
  'Palimbang',
  'Palo',
  'Palompon',
  'Paluan',
  'Pambujan',
  'Pamplona',
  'Panabo City',
  'Panaon',
  'Panay',
  'Pandacan',
  'Pandag',
  'Pandami',
  'Pandan',
  'Pandi',
  'Panganiban',
  'Pangantucan',
  'Pangil',
  'Panglao',
  'Panglima Estino',
  'Panglima Sugala',
  'Pangutaran',
  'Paniqui',
  'Panitan',
  'Pantabangan',
  'Pantao Ragat',
  'Pantar',
  'Pantukan',
  'Panukulan',
  'Paoay',
  'Paombong',
  'Paracale',
  'Paracelis',
  'Parañaque City',
  'Paranas',
  'Parang',
  'Pasacao',
  'Pasay City',
  'Pasig City',
  'Pasil',
  'Passi City',
  'Pastrana',
  'Pasuquin',
  'Pata',
  'Pateros',
  'Patikul',
  'Patnanungan',
  'Patnongon',
  'Pavia',
  'Payao',
  'Peñablanca',
  'Peñaranda',
  'Peñarrubia',
  'Perez',
  'Piagapo',
  'Piat',
  'Picong',
  'Piddig',
  'Pidigan',
  'Pigkawayan',
  'Pikit',
  'Pila',
  'Pilar',
  'Pili',
  'Pililla',
  'Pinabacdao',
  'Pinamalayan',
  'Pinamungahan',
  'Piñan',
  'Pinili',
  'Pintuyan',
  'Pinukpuk',
  'Pio Duran',
  'Pio V. Corpuz',
  'Pitogo',
  'Placer',
  'Plaridel',
  'Pola',
  'Polanco',
  'Polangui',
  'Polillo',
  'Polomolok',
  'Pontevedra',
  'Poona Bayabao',
  'Poona Piagapo',
  'Porac',
  'Poro',
  'Port Area',
  'Pototan',
  'Pozorrubio',
  'Pres. Carlos P. Garcia',
  'Pres. Manuel A. Roxas',
  'Presentacion',
  'President Quirino',
  'President Roxas',
  'Prieto Diaz',
  'Prosperidad',
  'Pualas',
  'Pudtol',
  'Puerto Galera',
  'Puerto Princesa City',
  'Pugo',
  'Pulilan',
  'Pulupandan',
  'Pura',
  'Quezon',
  'Quezon City',
  'Quiapo',
  'Quinapondan',
  'Quirino',
  'Ragay',
  'Rajah Buayan',
  'Ramon',
  'Ramon Magsaysay',
  'Ramos',
  'Rapu-Rapu',
  'Real',
  'Reina Mercedes',
  'Remedios T. Romualdez',
  'Rizal',
  'Rodriguez',
  'Romblon',
  'Ronda',
  'Rosales',
  'Rosario',
  'Roseller Lim',
  'Roxas',
  'Roxas City',
  'Sabangan',
  'Sablan',
  'Sablayan',
  'Sabtang',
  'Sadanga',
  'Sagada',
  'Sagay',
  'Sagay City',
  'Sagbayan',
  'Sagñay',
  'Saguday',
  'Saguiaran',
  'Saint Bernard',
  'Salay',
  'Salcedo',
  'Sallapadan',
  'Salug',
  'Salvador',
  'Salvador Benedicto',
  'Samal',
  'Samboan',
  'Sampaloc',
  'San Agustin',
  'San Andres',
  'San Antonio',
  'San Benito',
  'San Carlos City',
  'San Clemente',
  'San Dionisio',
  'San Emilio',
  'San Enrique',
  'San Esteban',
  'San Fabian',
  'San Felipe',
  'San Fernando',
  'San Fernando City',
  'San Francisco',
  'San Gabriel',
  'San Guillermo',
  'San Ildefonso',
  'San Isidro',
  'San Jacinto',
  'San Joaquin',
  'San Jorge',
  'San Jose',
  'San Jose City',
  'San Jose de Buan',
  'San Jose del Monte City',
  'San Juan',
  'San Juan City',
  'San Julian',
  'San Leonardo',
  'San Lorenzo',
  'San Lorenzo Ruiz',
  'San Luis',
  'San Manuel',
  'San Marcelino',
  'San Mariano',
  'San Mateo',
  'San Miguel',
  'San Narciso',
  'San Nicolas',
  'San Pablo',
  'San Pablo City',
  'San Pascual',
  'San Pedro City',
  'San Policarpo',
  'San Quintin',
  'San Rafael',
  'San Remigio',
  'San Ricardo',
  'San Roque',
  'San Sebastian',
  'San Simon',
  'San Teodoro',
  'San Vicente',
  'Sanchez-Mira',
  'Santa',
  'Santa Ana',
  'Santa Barbara',
  'Santa Catalina',
  'Santa Cruz',
  'Santa Elena',
  'Santa Fe',
  'Santa Ignacia',
  'Santa Josefa',
  'Santa Lucia',
  'Santa Magdalena',
  'Santa Marcela',
  'Santa Margarita',
  'Santa Maria',
  'Santa Monica',
  'Santa Praxedes',
  'Santa Rita',
  'Santa Rosa',
  'Santa Rosa City',
  'Santa Teresita',
  'Santander',
  'Santiago',
  'Santiago City',
  'Santo Domingo',
  'Santo Niño',
  'Santo Tomas',
  'Santol',
  'Sapa-Sapa',
  'Sapad',
  'Sapang Dalaga',
  'Sapi-An',
  'Sara',
  'Sarangani',
  'Sariaya',
  'Sarrat',
  'Sasmuan',
  'Sebaste',
  'Sen. Ninoy Aquino',
  'Sergio Osmeña Sr.',
  'Sevilla',
  'Shariff Aguak',
  'Shariff Saydona Mustapha',
  'Siasi',
  'Siaton',
  'Siay',
  'Siayan',
  'Sibagat',
  'Sibalom',
  'Sibonga',
  'Sibuco',
  'Sibulan',
  'Sibunag',
  'Sibutad',
  'Sibutu',
  'Sierra Bullones',
  'Sigay',
  'Sigma',
  'Sikatuna',
  'Silago',
  'Silang',
  'Silay City',
  'Silvino Lobos',
  'Simunul',
  'Sinacaban',
  'Sinait',
  'Sindangan',
  'Siniloan',
  'Siocon',
  'Sipalay City',
  'Sipocot',
  'Siquijor',
  'Sirawai',
  'Siruma',
  'Sison',
  'Sitangkai',
  'Socorro',
  'Sofronio Española',
  'Sogod',
  'Solana',
  'Solano',
  'Solsona',
  'Sominot',
  'Sorsogon City',
  'South Ubian',
  'South Upi',
  'Sual',
  'Subic',
  'Sudipen',
  'Sugbongcogon',
  'Sugpon',
  'Sulat',
  'Sulop',
  'Sultan Dumalondong',
  'Sultan Kudarat',
  'Sultan Mastura',
  'Sultan Naga Dimaporo',
  'Sultan Sa Barongis',
  'Sumilao',
  'Sumisip',
  'Surallah',
  'Surigao City',
  'Suyo',
  "T'Boli",
  'Taal',
  'Tabaco City',
  'Tabango',
  'Tabina',
  'Tabogon',
  'Tabontabon',
  'Tabuan-Lasa',
  'Tabuelan',
  'Tabuk City',
  'Tacloban City',
  'Tacurong City',
  'Tadian',
  'Taft',
  'Tagana-An',
  'Tagapul-An',
  'Tagaytay City',
  'Tagbilaran City',
  'Tagbina',
  'Tagkawayan',
  'Tago',
  'Tagoloan',
  'Tagoloan Ii',
  'Tagudin',
  'Taguig City',
  'Tagum City',
  'Talacogon',
  'Talaingod',
  'Talakag',
  'Talalora',
  'Talavera',
  'Talayan',
  'Talibon',
  'Talipao',
  'Talisay',
  'Talisay City',
  'Talisayan',
  'Talitay',
  'Talugtug',
  'Talusan',
  'Tambulig',
  'Tampakan',
  'Tamparan',
  'Tampilisan',
  'Tanauan',
  'Tanauan City',
  'Tanay',
  'Tandag City',
  'Tandubas',
  'Tangalan',
  'Tangcal',
  'Tangub City',
  'Tanjay City',
  'Tantangan',
  'Tanudan',
  'Tanza',
  'Tapaz',
  'Tapul',
  'Taraka',
  'Tarangnan',
  'Tarlac City',
  'Tarragona',
  'Tayabas City',
  'Tayasan',
  'Taysan',
  'Taytay',
  'Tayug',
  'Tayum',
  'Teresa',
  'Ternate',
  'Tiaong',
  'Tibiao',
  'Tigaon',
  'Tigbao',
  'Tigbauan',
  'Tinambac',
  'Tineg',
  'Tinglayan',
  'Tingloy',
  'Tinoc',
  'Tipo-Tipo',
  'Titay',
  'Tiwi',
  'Tobias Fornier',
  'Toboso',
  'Toledo City',
  'Tolosa',
  'Tomas Oppus',
  'Tondo I / Ii',
  'Tongkil',
  'Torrijos',
  'Trece Martires City',
  'Trento',
  'Trinidad',
  'Tuao',
  'Tuba',
  'Tubajon',
  'Tubao',
  'Tubaran',
  'Tubay',
  'Tubigon',
  'Tublay',
  'Tubo',
  'Tubod',
  'Tubungan',
  'Tuburan',
  'Tudela',
  'Tugaya',
  'Tuguegarao City',
  'Tukuran',
  'Tulunan',
  'Tumauini',
  'Tunga',
  'Tungawan',
  'Tupi',
  'Turtle Islands',
  'Tuy',
  'Ubay',
  'Umingan',
  'Ungkaya Pukan',
  'Unisan',
  'Upi',
  'Urbiztondo',
  'Urdaneta City',
  'Uson',
  'Uyugan',
  'Valderrama',
  'Valencia',
  'Valencia City',
  'Valenzuela City',
  'Valladolid',
  'Vallehermoso',
  'Veruela',
  'Victoria',
  'Victorias City',
  'Viga',
  'Vigan City',
  'Villaba',
  'Villanueva',
  'Villareal',
  'Villasis',
  'Villaverde',
  'Villaviciosa',
  'Vincenzo A. Sagun',
  'Vintar',
  'Vinzons',
  'Virac',
  'Wao',
  'Zamboanga City',
  'Zamboanguita',
  'Zaragoza',
  'Zarraga',
  'Zumarraga',
];

/**
 * Real typos / abbreviations / concatenations found in the live directory data that do not resolve
 * through the generic case/"City"-suffix matching in `normalizeCity`. Keys are lower-cased and
 * whitespace-collapsed; each value is the exact `PH_CITIES` entry to resolve to.
 */
const CITY_ALIASES: Readonly<Record<string, string>> = {
  zamboaga: 'Zamboanga City',
  'zamboanga i': 'Zamboanga City',
  isabella: 'Isabela City',
  'isabela basilan': 'Isabela City',
  'isabela city basilan': 'Isabela City',
  'sto tomas': 'Santo Tomas',
  'sto.tomas': 'Santo Tomas',
  cotabato: 'Cotabato City',
  toledo: 'Toledo City',
};

/** Lower-cased canonical entry -> canonical entry. Exact membership map, built once at module load. */
const CANONICAL_LOOKUP: ReadonlyMap<string, string> = new Map(
  PH_CITIES.map((city) => [city.toLowerCase(), city] as const),
);

/** Set of canonical entries, built once, for O(1) `isValidPhCity` membership tests. */
const PH_CITY_SET: ReadonlySet<string> = new Set(PH_CITIES);

/** Title-cases one hyphen-aware word, e.g. `lapu-lapu` -> `Lapu-Lapu`. */
function titleCaseWord(word: string): string {
  return word
    .split('-')
    .map((part) => (part.length === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('-');
}

/** Title-cases a whole place name, space-separated. */
function titleCase(s: string): string {
  return s.toLowerCase().split(' ').map(titleCaseWord).join(' ');
}

/**
 * Normalizes a free-text city into its canonical `PH_CITIES` spelling when confident, otherwise
 * returns a cleaned Title-Case version of the input unchanged. Pure and idempotent: never blanks or
 * drops data - an unrecognised place always survives so it can be surfaced (and rejected) rather than
 * silently lost.
 *
 * Resolution: trim/collapse whitespace, then test an ordered list of candidate keys against the
 * canonical map and the typo-alias map, most faithful first - the exact input, then the "City of X"
 * expansion, then the input with/without a trailing " City". Exact matches always win, so a
 * municipality ("San Fernando") and its same-named city ("San Fernando City") both round-trip to
 * themselves. If nothing matches, the cleaned input is Title-Cased and returned as-is.
 *
 * @param input Raw, possibly messy city text (or null/undefined).
 * @returns The canonical `PH_CITIES` entry, or a cleaned Title-Case fallback; `''` for blank input.
 */
export function normalizeCity(input: string | null | undefined): string {
  if (!input) return '';
  const collapsed = input.trim().replace(/\s+/g, ' ');
  if (!collapsed) return '';

  const lower = collapsed.toLowerCase();
  const endsWithCity = /\scity$/.test(lower);

  // Candidate keys in priority order; exact input first so `X` vs `X City` never cross-resolve.
  const candidates: string[] = [lower];
  const cityOf = lower.match(/^city of\s+(.+)$/);
  if (cityOf?.[1]) {
    const rest = cityOf[1];
    candidates.push(rest + ' city', rest);
  }
  if (endsWithCity) {
    candidates.push(lower.replace(/\scity$/, ''));
  } else {
    candidates.push(lower + ' city');
  }

  for (const key of candidates) {
    const hit = CANONICAL_LOOKUP.get(key) ?? CITY_ALIASES[key];
    if (hit) return hit;
  }

  return titleCase(collapsed);
}

/**
 * Strict membership test used by the profile validator and the picker: normalizes `input` and returns
 * whether the result is one of the 1423 canonical Philippine cities/municipalities. Case-,
 * whitespace-, "City"-suffix- and typo-tolerant via `normalizeCity`. Blank/unknown input is invalid.
 *
 * @param input Raw city text (or null/undefined).
 * @returns `true` iff `normalizeCity(input)` is an exact `PH_CITIES` member.
 */
export function isValidPhCity(input: string | null | undefined): boolean {
  return PH_CITY_SET.has(normalizeCity(input));
}
